### ISSUE TITLE
Memory footprint is big

### ISSUE THREAD

**Issue by julsemaan** [BurntSushi/rure-go#2]
First of all, I'm ready to be told I'm clearly using this library beyond what it was designed for.

So I've started using this library as I found the performance to be beyong Golang's regexp package for the use case I have.

Downside is, I have tens of thousands of regexs and the memory footprint of each rure.Regex is fairly large.

In the script below, you can see that creating 10K regex results in ~450MB of RAM being used.

Could there be a need for memory optimization in this library or is this to be expected ?

Thanks!

```
package main

import (
  "fmt"
  "time"
  
  rure "github.com/BurntSushi/rure-go"
) 
  
func main() {
  l := []*rure.Regex{}
  for i := 0; i < 1000; i++ {
    r, _ := rure.Compile(`\w*(?P<last>\w)`)
    l = append(l, r)
  } 
    
  for {
    fmt.Println("loop")
    time.Sleep(1 * time.Second)
  }
}
```

**Comment by BurntSushi** [comment]
> Could there be a need for memory optimization

There is always room for improvement, but what you're seeing does not sound ridiculous to me. Your numbers work out to roughly 45KB per regex. The regex you're building is also not exactly small, since `\w` is a Unicode character class (use `(?-u:\w)` for an ASCII only character class). Potentially even worse, you're only seemingly measuring the size of a compiled regex. A regex will actually build more machinery at match time and use more memory.

Also, this library is just a binding, so if there were memory optimization to be done, it would be in the Rust regex library itself: https://github.com/rust-lang/regex

In general, trying to match "tens of thousands of regexes" is a fairly specialized problem that will require specialized tools. General purpose regex libraries have their limits. You might consider checking out Hyperscan as something that specifically specializes in large numbers of patterns. Your other choice might be using a library like Ragel or re2c to build your regexes up front in the source code itself (essentially trading heap space for code size).

**Comment by julsemaan** [comment]
@BurntSushi 

Thanks for the detailed explanation, I'll make sure I check your recommendations.
