### ISSUE TITLE
In Mac OSX m1 can't work!

### ISSUE THREAD

**Issue by smarttang** [BurntSushi/rure-go#7]
# github.com/BurntSushi/rure-go
ld: library not found for -lrure
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by BurntSushi** [comment]
You haven't provided enough details for anyone to help you. My guess is that you haven't configured your environment correctly. The error is pretty clear: your linker can't find the compiled `rure` library. So either you didn't compile it or you aren't telling your linker where to find it. The README pretty clearly states the directions for making this work.

If this is for some reason an m1 macOS specific problem, then I can't help you because I don't have an m1 mac.

**Comment by smarttang** [comment]
ok，I can't use this module，use default golang regex finish my work。
thank you!
